version: '3'

services:
  app:
    image: node:lts-alpine
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: |
      sh -c "
      npm install &&
      npm start
      "
    networks:
      - demo_app_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    networks:
      - demo_app_network
networks:
  demo_app_network:
